apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values. }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{ - include "hello-world.selectorLabels" . | nindent 4 }}
